format:
    # Colors can be found here : https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html.
    text-color: 'NONE' # color of the text (c.f. - make the tag most visible), none for auto
    chat: '{prefix}{player-name}'
    action-bar: '&6{player-name} &7mentioned you.'

options:
    update-notifier: true # check update on starting

    mysql:
        enabled: true
        host: localhost
        port: 3306
        database: mentions
        user: mention
        password: noitnem

    anti-spam:
        enable: true
        interval: 5 # in second

    gui: true
    tab-complete: true

    hook:
        placeholderapi: true
        deluxechat: true

    prefix:
        custom: true
        force:
            actionbar: 'a'
            mention: 'm'
            popup: 'p'
            sound: 's'
            visible: 'v'
        value: '&6&l@'

    popup:
        enabled: true # NEVER /reload THE SERVER
        allow-out-of-boxes: false
        icon:
            minecraft: 'book'
        title:
          '1': '&aNew mention !'
          '2': '&b{player}&7, from &e{who}'
          '3': ''

    default: # default values
        action-bar: true
        color: Orange # list of all colors and correspondence : https://github.com/Triozer/spigot-mention-player/blob/master/src/colors.
        mention: true
        popup: true
        sound: true
        visible: false
        # Sounds by version can be found here: https://gist.github.com/Triozer/3579ac01cdec67e7331811c01089d325.
        # For 1.8 please change this to : NOTE_PLING
        # For 1.12 please change this to : NOTE_PLING
        # For 1.12 please change this to : NOTE_PLING
        notification: 'BLOCK_NOTE_BLOCK_PLING'

    permission:
        bypass:
            action-bar: 'mention.bypass.action-bar' # force sending mention to the action bar.
            anti-spam: 'mention.bypass.anti-spam' # bypass the anti-spam interval.
            mention: 'mention.bypass.mention' # force mentioning a player.
            popup: 'mention.bypass.popup' # force showing a popup on mention.
            sound: 'mention.bypass.sound' # force playing a sound on mention.
        color:
            use: 'mention.color.use' # permission to change mention color in the GUI.
            black: 'mention.color.black'
            blue: 'mention.color.blue'
            cyan: 'mention.color.cyan'
            dark-aqua: 'mention.color.dark-aqua'
            dark-gray: 'mention.color.dark-gray'
            dark-green: 'mention.color.dark-green'
            dark-purple: 'mention.color.dark-purple'
            dark-red: 'mention.color.dark-red'
            green: 'mention.color.green'
            orange: 'mention.color.orange'
            light-gray: 'mention.color.light-gray'
            light-purple: 'mention.color.light-purple'
            red: 'mention.color.red'
            white: 'mention.color.white'
            yellow: 'mention.color.yellow'
            rainbow: 'mention.color.rainbow'
