format:
    # Colors can be found here : https://hub.spigotmc.org/javadocs/spigot/org/bukkit/ChatColor.html.
    text-color: "GRAY"
    chat: "&6&l@{player-name}"
    action-bar: "&6{player-name} &7mentioned you."

message:
    action-bar-on: "&aMentions will now be displayed in the action bar."
    action-bar-off: "&cMentions will no longer be displayed in the action bar."
    sound-on: "&aMentions sound is now activated."
    sound-off: "&cMentions sound is now deactivated."
    toggle-on: "&aYou can now be mentioned."
    toggle-off: "&cYou can no longer be mentioned."
    error:
        already-on: "&cMentions is already toggled on."
        already-off: "&ccMentions is already toggled off."
        action-bar-already-on: "&cMentions is already toggle on for the action bar."
        action-bar-already-off: "&cMentions is already toggled off for the action bar."
        sound-already-on: "&cMentions sound is already toggled on."
        sound-already-off: "&cMentions sound is already toggled off."
        spam: "§cYou can't spam like this."

option:
    anti-spam:
        enable: true
        interval: 5 # in second
    # Sounds by version can be found here: https://gist.github.com/Triozer/3579ac01cdec67e7331811c01089d325.
    # For 1.8 please change this to : NOTE_PLING
    gui: true # Need SmartInvs (https://www.spigotmc.org/resources/smartinvs-advanced-inventory-api.42835/) to works
    sound: "BLOCK_NOTE_PLING"
    tab-complete: true
    default: # default value
        action-bar: true
        mention: true
        sound: true
    permission:
        bypass-action-bar: "mention.bypass-action-bar" # force sending mention to the action bar.
        bypass-mention: "mention.bypass-mention" # force mentioning a player who does not accept the mentions.
        bypass-reload: "mention.bypass.reload" # reload the configuration file.
        bypass-sound: "mention.bypass-sound" # force playing sound by mentioning a player who does not allow sounds.
