name: MentionPlayer

main: fr.triozer.mentionplayer.MentionPlayer
author: Triozer
website: https://c-dric.eu
version: 1.13.4

description: Mention a player.

commands:
    mention:
        description: Change your settings.
